# Generated by Django 5.2.17 on 2026-10-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('profile_image', 'Profile Image'), ('project_image', 'Project Image'), ('resume', 'Resume'), ('certificate', 'Certificate'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=50)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('cloudinary_url', models.URLField(blank=True, default='', max_length=1000)),
                ('cloudinary_resource_type', models.CharField(default='image', max_length=50)),
                ('delivery_type', models.CharField(default='upload', max_length=50)),
                ('file_format', models.CharField(max_length=20)),
                ('verified_content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], db_index=True, default='private', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='portfolios.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['client', 'visibility'], name='media_manag_client__ff7e7d_idx'), models.Index(fields=['client', 'category'], name='media_manag_client__446c9b_idx'), models.Index(fields=['cloudinary_public_id'], name='media_manag_cloudin_22b6c1_idx')],
            },
        ),
    ]
