# Generated by Django 5.2.17 on 2026-10-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='clients.client')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['client', '-start_date'], name='portfolios__client__127fe0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='clients.client')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['client', '-start_date'], name='portfolios__client__acdd67_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('featured_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('tech_stack', models.CharField(help_text='Comma-separated skills/technologies e.g. Python, Django, Tailwind', max_length=500)),
                ('project_url', models.URLField(blank=True, default='', max_length=500)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['client', 'is_published'], name='portfolios__client__cb8f6d_idx'), models.Index(fields=['client', 'slug'], name='portfolios__client__3506f1_idx')],
                'unique_together': {('client', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='General', help_text='e.g. Frontend, Backend, DevOps, Languages', max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Proficiency percentage 0-100')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='clients.client')),
            ],
            options={
                'ordering': ['order', 'category', 'name'],
                'indexes': [models.Index(fields=['client', 'category'], name='portfolios__client__ae0155_idx')],
            },
        ),
    ]
