# Generated by Django 5.2.17 on 2026-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('bio', models.TextField()),
                ('profile_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('website_url', models.URLField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='clients_cli_slug_fa0348_idx'), models.Index(fields=['is_published'], name='clients_cli_is_publ_5608bb_idx')],
            },
        ),
    ]
