# Generated by Django 5.2.17 on 2026-10-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_facebook_url_client_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='client',
            name='youtube_url',
        ),
    ]
