# Generated by Django 5.0.6 on 2026-10-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='instagram_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='twitter_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
