# Generated by Django 5.0.6 on 2026-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_social_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portfolio_style',
            field=models.CharField(choices=[('modern_dark', 'Modern Dark (Cyan / Cyberpunk)'), ('executive_light', 'Executive Light (Navy / Slate Clean)'), ('creative_gradient', 'Creative Glass (Purple & Emerald)'), ('minimal_bento', 'Bento Grid (Dark / Amber & Charcoal)'), ('terminal_retro', 'Terminal Hacker (Retro Monospace / Emerald)')], default='modern_dark', help_text='Layout style & theme for public portfolio', max_length=50),
        ),
    ]
