# Generated by Django 5.2.17 on 2026-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_portfolio_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_published',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='portfolio_style',
            field=models.CharField(blank=True, choices=[('modern_dark', 'Modern Dark (Cyan / Cyberpunk)'), ('executive_light', 'Executive Light (Navy / Slate Clean)'), ('creative_gradient', 'Creative Glass (Purple & Emerald)'), ('minimal_bento', 'Bento Grid (Dark / Amber & Charcoal)'), ('terminal_retro', 'Terminal Hacker (Retro Monospace / Emerald)')], default='modern_dark', help_text='Layout style & theme for public portfolio', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
